export const ActionTypes = {
    //fakestoreapi
    FETCH_PRODUCTS : "FETCH_PRODUCTS",
    FETCH_CATEGORY:"FETCH_CATEGORY",
    SET_PRODUCTS : "SET_PRODUCT",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
}